frontend:
  image:
    repository: ghcr.io/srinivas-aapmor/ats-frontend
    tag: v1
  replicaCount: 1
  service:
    type: NodePort
    port: 3000

backend:
  image:
    repository: ghcr.io/srinivas-aapmor/ats-backend
    tag: v1
  replicaCount: 1
  service:
    type: NodePort
    port: 5000
  env:
    - name: S3_REGION
      value: "us-east-1"
    - name: S3_BUCKET_NAME
      value: "cv-test-python-api"
    - name: AWS_ACCESS_KEY
      value: ""
    - name: AWS_SECRET_KEY
      value: ""
    - name: MONGO_URI
      value: ""
    - name: OPENAI_API_KEY
      value: ""



ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: [] 
